import type { ExceptionSeverity } from "@payrecon/domain";

/**
 * The persistence port for notifications.
 *
 * Every method takes `organizationId` as a required leading argument rather
 * than as an optional filter, so an unscoped read or write is not expressible
 * through this API. The one exception is `claimDueDeliveries`, which is
 * inherently cross-tenant because a single worker drains the whole queue; the
 * rows it returns carry their `organizationId`, and every subsequent operation
 * on them is scoped by it.
 *
 * The interface exists so that the dedupe, threshold and retry logic in
 * `delivery.ts` can be exercised by unit tests with no database, while
 * production uses the Drizzle adapter in `store-drizzle.ts` whose queries are
 * all `organization_id`-scoped. See `memory-store.ts` for the test double,
 * which enforces the same `(organization_id, dedupe_key)` uniqueness the
 * database index does.
 */

export type NotificationKind = "email" | "slack";
export type DestinationStatus = "pending_verification" | "active" | "disabled" | "failing";
export type NotificationDigest = "immediate" | "hourly" | "daily";
export type DeliveryStatus = "pending" | "sent" | "failed" | "skipped";

/** Audit actions this package is allowed to write. Subset of `AuditAction`. */
export type NotificationAuditAction =
  | "notification.destination_created"
  | "notification.destination_verified"
  | "notification.destination_deleted"
  | "notification.policy_changed"
  | "notification.test_sent"
  | "notification.delivery_failed";

export interface NotificationAuditInput {
  organizationId: string;
  actor: { type: "user" | "api_key" | "system"; userId?: string | null };
  action: NotificationAuditAction;
  targetType?: string | undefined;
  targetId?: string | undefined;
  /** Redacted before it is written. Never put a webhook URL or key material here. */
  metadata?: Record<string, unknown> | undefined;
}

// ---------------------------------------------------------------------------
// Rows
// ---------------------------------------------------------------------------

export interface DestinationRow {
  id: string;
  organizationId: string;
  kind: NotificationKind;
  name: string;
  /** Email address for `email` destinations; null for `slack`. */
  target: string | null;
  secretCiphertext: Buffer | null;
  secretNonce: Buffer | null;
  secretAuthTag: Buffer | null;
  secretKeyId: string | null;
  secretHint: string | null;
  status: DestinationStatus;
  verifiedAt: Date | null;
  lastErrorAt: Date | null;
  lastError: string | null;
  createdByUserId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface NewDestinationRow {
  /** Generated by the caller, because the AAD binds the ciphertext to this id. */
  id: string;
  organizationId: string;
  kind: NotificationKind;
  name: string;
  target: string | null;
  secretCiphertext: Buffer | null;
  secretNonce: Buffer | null;
  secretAuthTag: Buffer | null;
  secretKeyId: string | null;
  secretHint: string | null;
  status: DestinationStatus;
  createdByUserId: string | null;
  createdAt: Date;
}

export interface DestinationPatch {
  status?: DestinationStatus;
  verifiedAt?: Date | null;
  lastError?: string | null;
  lastErrorAt?: Date | null;
  updatedAt: Date;
}

export interface PolicyRow {
  id: string;
  organizationId: string;
  destinationId: string;
  minSeverity: ExceptionSeverity;
  minRevenueAtRiskMinor: bigint | null;
  currency: string | null;
  digest: NotificationDigest;
  criticalBypassesDigest: boolean;
  enabled: boolean;
}

export interface DeliveryRow {
  id: string;
  organizationId: string;
  policyId: string | null;
  destinationId: string;
  dedupeKey: string;
  status: DeliveryStatus;
  attempts: number;
  summary: Record<string, unknown>;
  exceptionCount: number;
  scheduledFor: Date;
  sentAt: Date | null;
  lastError: string | null;
  createdAt: Date;
}

export interface NewDeliveryRow {
  id: string;
  organizationId: string;
  policyId: string;
  destinationId: string;
  dedupeKey: string;
  scheduledFor: Date;
  createdAt: Date;
}

export interface DeliveryPatch {
  status: DeliveryStatus;
  attempts: number;
  scheduledFor?: Date;
  sentAt?: Date | null;
  lastError?: string | null;
  summary?: Record<string, unknown>;
}

/** The minimal exception projection a message needs. Nothing more is read. */
export interface ExceptionRow {
  id: string;
  organizationId: string;
  ruleId: string;
  severity: ExceptionSeverity;
  summary: string;
  revenueAtRiskMinor: bigint | null;
  currency: string | null;
}

// ---------------------------------------------------------------------------
// Port
// ---------------------------------------------------------------------------

export interface NotificationStore {
  insertDestination(row: NewDestinationRow): Promise<DestinationRow>;
  getDestination(organizationId: string, destinationId: string): Promise<DestinationRow | null>;
  updateDestination(
    organizationId: string,
    destinationId: string,
    patch: DestinationPatch,
  ): Promise<DestinationRow | null>;
  deleteDestination(organizationId: string, destinationId: string): Promise<boolean>;

  /** Enabled policies only; disabled ones must never produce a delivery. */
  listEnabledPolicies(organizationId: string): Promise<PolicyRow[]>;

  /**
   * Insert a delivery, relying on the unique `(organization_id, dedupe_key)`
   * index to collapse races. Returns the surviving row's id and whether this
   * call created it.
   */
  insertDeliveryIfAbsent(row: NewDeliveryRow): Promise<{ id: string; created: boolean }>;

  /**
   * Record that a delivery covers an exception. Returns false when the link
   * already existed. Implementations must keep `exceptionCount` consistent with
   * the number of linked rows.
   */
  linkException(organizationId: string, deliveryId: string, exceptionId: string): Promise<boolean>;

  /**
   * Atomically take ownership of due pending deliveries by pushing
   * `scheduledFor` out to `leaseUntil`, so a second worker running concurrently
   * cannot pick up the same rows.
   */
  claimDueDeliveries(now: Date, limit: number, leaseUntil: Date): Promise<DeliveryRow[]>;

  getDelivery(organizationId: string, deliveryId: string): Promise<DeliveryRow | null>;
  listDeliveryExceptions(organizationId: string, deliveryId: string): Promise<ExceptionRow[]>;
  updateDelivery(organizationId: string, deliveryId: string, patch: DeliveryPatch): Promise<void>;

  getOrganizationName(organizationId: string): Promise<string | null>;

  recordAudit(input: NotificationAuditInput): Promise<void>;
}
